# Generated by Django 3.1.7 on 2021-03-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='name',
        ),
        migrations.AlterField(
            model_name='cards',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
