# Generated by Django 3.1.7 on 2021-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcards', '0002_auto_20210318_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
