# Generated by Django 3.1.7 on 2021-03-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcards', '0003_cards_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='static/images')),
                ('playedby', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cards',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
