# Generated by Django 3.1.7 on 2021-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcards', '0004_auto_20210318_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
